# Generated by Django 5.2.14 on 2026-05-18 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=160, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=24, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Группа баннеров',
                'verbose_name_plural': 'Группы баннеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='banners.bannergroup', verbose_name='Группа баннеров')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заголовок креатива',
                'verbose_name_plural': 'Заголовки креативов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='banners/images/', verbose_name='Изображение')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.bannergroup', verbose_name='Группа баннеров')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Картинка креатива',
                'verbose_name_plural': 'Картинки креативов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=24, verbose_name='Статус')),
                ('utm_key', models.CharField(max_length=120, unique=True, verbose_name='UTM-метка баннера')),
                ('target_url', models.URLField(blank=True, verbose_name='Вторая ссылка')),
                ('priority', models.PositiveSmallIntegerField(default=50, verbose_name='Приоритет')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.bannergroup', verbose_name='Группа баннеров')),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='banners.creativeheadline', verbose_name='Заголовок')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='banners.creativeimage', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bannergroup',
            index=models.Index(fields=['owner', 'created_at'], name='banners_ban_owner_i_cd15bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bannergroup',
            index=models.Index(fields=['status', 'created_at'], name='banners_ban_status_5c4d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['group', 'status'], name='banners_ban_group_i_f243a5_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['owner', 'created_at'], name='banners_ban_owner_i_c25607_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['priority', 'status'], name='banners_ban_priorit_274222_idx'),
        ),
    ]
