# Generated by Django 5.2.14 on 2026-05-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.creativeheadline', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.creativeimage', verbose_name='Картинка'),
        ),
    ]
