# Generated by Django 5.2.14 on 2026-05-18 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0005_article_outbound_mark_custom_value_and_more'),
        ('banners', '0002_alter_banner_headline_alter_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bannergroup',
            name='article_groups',
            field=models.ManyToManyField(blank=True, related_name='banner_groups', to='articles.articlegroup', verbose_name='Группы статей'),
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='banner_groups', to='articles.article', verbose_name='Статьи'),
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='slot',
            field=models.CharField(choices=[('top_left', 'Верхний левый'), ('top_right', 'Верхний правый'), ('in_article', 'Внутри статьи'), ('sidebar_1', 'Боковой 1'), ('sidebar_2', 'Боковой 2'), ('sidebar_wide', 'Боковой широкий'), ('popup', 'Pop-up')], default='sidebar_1', max_length=32, verbose_name='Слот показа'),
        ),
        migrations.AddIndex(
            model_name='bannergroup',
            index=models.Index(fields=['slot', 'status'], name='banners_ban_slot_51ad77_idx'),
        ),
    ]
