# Generated by Django 5.2.14 on 2026-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_bannergroup_article_groups_bannergroup_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannergroup',
            name='excluded_slots',
            field=models.JSONField(blank=True, default=list, verbose_name='Не показывать в слотах'),
        ),
    ]
