# Generated by Django 5.2.14 on 2026-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_bannergroup_excluded_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannergroup',
            name='target_url',
            field=models.URLField(blank=True, verbose_name='Рекламная ссылка'),
        ),
    ]
