# Generated by Django 5.2.14 on 2026-05-21 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('banners', '0005_bannergroup_target_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='display_tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первый эшелон'), (2, 'Второй эшелон')], default=1, verbose_name='Эшелон показа'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['display_tier', 'status'], name='banners_ban_display_3bf068_idx'),
        ),
    ]
