# Generated by Django 5.2.14 on 2026-05-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0006_alter_article_status'),
        ('banners', '0006_banner_display_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slot', models.CharField(choices=[('top_left', 'Верхний левый'), ('top_right', 'Верхний правый'), ('in_article', 'Внутри статьи'), ('sidebar_1', 'Боковой 1'), ('sidebar_2', 'Боковой 2'), ('sidebar_wide', 'Боковой широкий'), ('popup', 'Pop-up')], max_length=32, verbose_name='Слот')),
                ('display_tier', models.PositiveSmallIntegerField(choices=[(1, 'Первый эшелон'), (2, 'Второй эшелон')], default=1, verbose_name='Эшелон показа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_placements', to='articles.article', verbose_name='Статья')),
                ('article_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_placements', to='articles.articlegroup', verbose_name='Группа статей')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='banners.banner', verbose_name='Закрепленный баннер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Закрепление баннера',
                'verbose_name_plural': 'Закрепления баннеров',
                'ordering': ['slot', 'display_tier'],
                'indexes': [models.Index(fields=['article', 'slot', 'display_tier'], name='banners_ban_article_4a2c2c_idx'), models.Index(fields=['article_group', 'slot', 'display_tier'], name='banners_ban_article_643654_idx'), models.Index(fields=['banner', 'is_active'], name='banners_ban_banner__e551b2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('article__isnull', False)), fields=('article', 'slot', 'display_tier'), name='unique_article_banner_placement'), models.UniqueConstraint(condition=models.Q(('article_group__isnull', False)), fields=('article_group', 'slot', 'display_tier'), name='unique_article_group_banner_placement')],
            },
        ),
    ]
