# Generated by Django 5.2.14 on 2026-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_bannerplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='target_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Вторая ссылка'),
        ),
        migrations.AlterField(
            model_name='bannergroup',
            name='target_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Рекламная ссылка'),
        ),
    ]
