# Generated by Django 5.2.14 on 2026-05-21 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_alter_banner_target_url_alter_bannergroup_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_utm_param',
            field=models.CharField(blank=True, help_text='Если пусто, используется настройка группы.', max_length=64, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='Имя UTM-параметра баннера'),
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='banner_utm_param',
            field=models.CharField(default='ad_vtr_name', help_text='Параметр, в который подставляется UTM/tracking key баннера.', max_length=64, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='Имя UTM-параметра баннера'),
        ),
    ]
