# Generated by Django 5.2.14 on 2026-05-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=280, verbose_name='Slug')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Страна')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='Язык')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Изображение')),
                ('body', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешний ленд')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('archived', 'Архив')], default='draft', max_length=24, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='articles_ar_status_cbb22b_idx'), models.Index(fields=['owner', 'created_at'], name='articles_ar_owner_i_bcfc54_idx')],
            },
        ),
    ]
