# Generated by Django 5.2.14 on 2026-05-15 16:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст статьи'),
        ),
    ]
