# Generated by Django 5.2.14 on 2026-05-15 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0002_alter_article_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('internal', 'Статья на платформе'), ('external', 'Внешний ленд')], default='internal', max_length=24, verbose_name='Тип статьи'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', 'status'], name='articles_ar_article_0501b3_idx'),
        ),
    ]
