# Generated by Django 5.2.14 on 2026-05-18 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0003_article_article_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Вертикаль',
                'verbose_name_plural': 'Вертикали',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='html_file',
            field=models.FileField(blank=True, upload_to='articles/html/', verbose_name='HTML-файл'),
        ),
        migrations.AddField(
            model_name='article',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('internal', 'Статья на платформе'), ('external', 'Внешний ленд'), ('html', 'HTML-файл')], default='internal', max_length=24, verbose_name='Тип статьи'),
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=160, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, max_length=180, verbose_name='Slug')),
                ('geo', models.CharField(blank=True, max_length=2, verbose_name='GEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_groups', to='articles.vertical', verbose_name='Вертикаль')),
            ],
            options={
                'verbose_name': 'Группа статей',
                'verbose_name_plural': 'Группы статей',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.articlegroup', verbose_name='Группы статей'),
        ),
        migrations.AddField(
            model_name='article',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.vertical', verbose_name='Вертикаль'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['country', 'vertical'], name='articles_ar_country_2fad00_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['public_id'], name='articles_ar_public__412f08_idx'),
        ),
        migrations.AddIndex(
            model_name='articlegroup',
            index=models.Index(fields=['owner', 'created_at'], name='articles_ar_owner_i_9c1e17_idx'),
        ),
        migrations.AddIndex(
            model_name='articlegroup',
            index=models.Index(fields=['geo', 'vertical'], name='articles_ar_geo_9e767d_idx'),
        ),
    ]
