# Generated by Django 5.2.14 on 2026-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_vertical_article_html_file_article_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outbound_mark_custom_value',
            field=models.CharField(blank=True, max_length=160, verbose_name='Свое значение UTM/параметра'),
        ),
        migrations.AddField(
            model_name='article',
            name='outbound_mark_enabled',
            field=models.BooleanField(default=True, verbose_name='Добавлять метку к исходящим ссылкам'),
        ),
        migrations.AddField(
            model_name='article',
            name='outbound_mark_param',
            field=models.CharField(default='article_id', max_length=80, verbose_name='Имя UTM/параметра'),
        ),
        migrations.AddField(
            model_name='article',
            name='outbound_mark_replace_existing',
            field=models.BooleanField(default=False, verbose_name='Перезаписывать существующий параметр'),
        ),
        migrations.AddField(
            model_name='article',
            name='outbound_mark_value_mode',
            field=models.CharField(choices=[('article_id', 'ID статьи'), ('public_id', 'Публичный ID'), ('custom', 'Свое значение')], default='article_id', max_length=24, verbose_name='Значение UTM/параметра'),
        ),
    ]
