# Generated by Django 5.2.14 on 2026-05-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_outbound_mark_custom_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=24, verbose_name='Статус'),
        ),
    ]
