# Generated by Django 5.2.14 on 2026-05-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_status'),
        ('tracking', '0003_trackerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tracker_profile',
            field=models.ForeignKey(blank=True, help_text='Если пусто, используется профиль первой группы статьи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tracking.trackerprofile', verbose_name='Профиль трекера'),
        ),
        migrations.AddField(
            model_name='articlegroup',
            name='tracker_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_groups', to='tracking.trackerprofile', verbose_name='Профиль трекера'),
        ),
    ]
