# Generated by Django 5.2.14 on 2026-05-25 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0008_article_group_rotation'),
        ('tracking', '0003_trackerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroup',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=24, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='articlegroup',
            index=models.Index(fields=['status', 'created_at'], name='articles_ar_status_f765aa_idx'),
        ),
    ]
