# Generated by Django 5.2.14 on 2026-05-26 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlegroup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='engagement_event_enabled',
            field=models.BooleanField(default=False, help_text='Срабатывает один раз: больше 60 секунд на статье, скролл 25%+ и клик по баннеру или следующей статье.', verbose_name='Отправлять событие вовлеченного клика'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_event_param',
            field=models.CharField(default='event30', help_text='Например event30. Этот параметр будет отправлен в профиль трекера.', max_length=80, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='Параметр события в трекере'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_event_value',
            field=models.CharField(default='1', max_length=80, verbose_name='Значение события'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_utm_param',
            field=models.CharField(blank=True, default='utm_content', help_text='Будет добавлен к URL баннера или следующей статьи при срабатывании события. Оставьте пустым, если метка не нужна.', max_length=80, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='UTM-параметр для клика'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_utm_value',
            field=models.CharField(blank=True, default='engaged_click', max_length=160, verbose_name='UTM-значение для клика'),
        ),
    ]
