# Generated by Django 5.2.14 on 2026-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_engagement_event_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='next_article_groups',
            field=models.ManyToManyField(blank=True, help_text='Если пусто, используются настройки группы входа или группы самой статьи.', related_name='next_feed_articles', to='articles.articlegroup', verbose_name='Группы для нижней ленты'),
        ),
        migrations.AddField(
            model_name='articlegroup',
            name='next_article_groups',
            field=models.ManyToManyField(blank=True, help_text='Если пусто, в нижней ленте используются статьи из этой группы.', related_name='used_as_next_feed_for', symmetrical=False, to='articles.articlegroup', verbose_name='Группы для блока "Другие статьи"'),
        ),
    ]
