# Generated by Django 5.2.14 on 2026-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_next_article_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroup',
            name='ui_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français'), ('pt', 'Português'), ('es', 'Español')], default='ru', help_text='Язык кнопок и служебных текстов на публичных статьях этой группы.', max_length=8, verbose_name='Язык интерфейса витрины'),
        ),
    ]
