# Generated by Django 5.2.14 on 2026-05-28 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articlegroup_ui_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_utm_key',
            field=models.CharField(blank=True, help_text='Эта метка подставляется в ad_vtr_name и выбранный UTM-параметр статьи.', max_length=120, verbose_name='UTM-метка статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_utm_param',
            field=models.CharField(default='ad_vtr_name', help_text='Например: ad_vtr_name. В этот параметр будет подставляться UTM-метка статьи.', max_length=80, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='Имя UTM-параметра статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_tracker_url',
            field=models.URLField(blank=True, help_text='Если заполнено, событие вовлеченности отправляется сюда. Если пусто, используется ссылка из профиля трекера.', max_length=2000, verbose_name='Ссылка трекера для события вовлеченности'),
        ),
    ]
