# Generated by Django 5.2.14 on 2026-05-28 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_tracking_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_utm_param',
            field=models.CharField(default='article_name', help_text='Например: article_name. В этот параметр будет подставляться UTM-метка статьи.', max_length=80, validators=[django.core.validators.RegexValidator(message='Имя параметра может содержать латинские буквы, цифры, "_", "." и "-", но должно начинаться с буквы или "_".', regex='^[A-Za-z_][A-Za-z0-9_.-]*$')], verbose_name='Имя UTM-параметра статьи'),
        ),
    ]
