# Generated by Django 5.2.14 on 2026-05-15 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Домен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Источник трафика',
                'verbose_name_plural': 'Источники трафика',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='Название потока')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('design', models.CharField(blank=True, max_length=80, verbose_name='Дизайн')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=24, verbose_name='Статус')),
                ('no_redirect', models.BooleanField(default=False, verbose_name='Без редиректа')),
                ('collect_push_base', models.BooleanField(default=False, verbose_name='Сбор push-базы')),
                ('show_back_button', models.BooleanField(default=True, verbose_name='Кнопка Назад')),
                ('show_popup', models.BooleanField(default=True, verbose_name='Показ Pop-Up')),
                ('analytics_enabled', models.BooleanField(default=True, verbose_name='Системы аналитики')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='articles.article', verbose_name='Статья')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='flows.domain', verbose_name='Домен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
                ('traffic_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='flows.trafficsource', verbose_name='Источник трафика')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='flows_flow_status_c659a6_idx'), models.Index(fields=['owner', 'created_at'], name='flows_flow_owner_i_8f2cb0_idx'), models.Index(fields=['public_id'], name='flows_flow_public__e1b6ec_idx')],
            },
        ),
    ]
