# Generated by Django 5.2.14 on 2026-05-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
        ('flows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('click_id', models.CharField(db_index=True, max_length=255, verbose_name='Click ID')),
                ('partner', models.CharField(blank=True, max_length=120, verbose_name='Партнерская программа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('approved', 'Апрув'), ('rejected', 'Отклонен'), ('hold', 'Холд')], default='new', max_length=24, verbose_name='Статус')),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выплата')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Валюта')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw payload')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_events', to='flows.flow', verbose_name='Поток')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Postback',
                'verbose_name_plural': 'Postback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['click_id', 'created_at'], name='tracking_po_click_i_4a6444_idx'), models.Index(fields=['status', 'created_at'], name='tracking_po_status_386e75_idx'), models.Index(fields=['owner', 'created_at'], name='tracking_po_owner_i_96a970_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('click', 'Клик'), ('pageview', 'Просмотр')], max_length=24, verbose_name='Тип события')),
                ('click_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Click ID из трекера')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры перехода')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_events', to='articles.article', verbose_name='Статья')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_events', to='flows.flow', verbose_name='Поток')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Событие визита',
                'verbose_name_plural': 'События визитов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flow', 'event_type', 'created_at'], name='tracking_vi_flow_id_9e0c92_idx'), models.Index(fields=['owner', 'created_at'], name='tracking_vi_owner_i_bf78f9_idx')],
            },
        ),
    ]
