# Generated by Django 5.2.14 on 2026-05-18 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0005_article_outbound_mark_custom_value_and_more'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(db_index=True, max_length=40, verbose_name='Тип события')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Session ID')),
                ('click_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Click ID из трекера')),
                ('target_url', models.URLField(blank=True, verbose_name='Целевая ссылка')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('scroll_depth', models.PositiveSmallIntegerField(default=0, verbose_name='Глубина скролла, %')),
                ('time_on_page', models.PositiveIntegerField(default=0, verbose_name='Время на странице, сек.')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры входа')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_events', to='articles.article', verbose_name='Статья')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Поведенческое событие статьи',
                'verbose_name_plural': 'Поведенческие события статей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'event_type', 'created_at'], name='tracking_ar_article_78bbbf_idx'), models.Index(fields=['owner', 'created_at'], name='tracking_ar_owner_i_19b1a8_idx'), models.Index(fields=['session_id', 'created_at'], name='tracking_ar_session_ad4613_idx')],
            },
        ),
    ]
