# Generated by Django 5.2.14 on 2026-05-21 11:01

import django.db.models.deletion
import tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tracking', '0002_articlebehaviorevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=160, verbose_name='Название профиля')),
                ('endpoint_url', models.URLField(max_length=2000, verbose_name='Ссылка трекера')),
                ('inbound_click_id_param', models.CharField(default='clickid', max_length=80, verbose_name='Параметр clickid во входящей ссылке')),
                ('update_click_id_param', models.CharField(default='upd_clickid', max_length=80, verbose_name='Параметр clickid для отправки в трекер')),
                ('event_value', models.CharField(default='1', max_length=40, verbose_name='Значение события')),
                ('event_params', models.JSONField(blank=True, default=tracking.models.default_tracker_events, verbose_name='Параметры событий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Профиль трекера',
                'verbose_name_plural': 'Профили трекеров',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='tracking_tr_owner_i_8f21ce_idx'), models.Index(fields=['is_active', 'created_at'], name='tracking_tr_is_acti_3ef28b_idx')],
            },
        ),
    ]
